workflows:
  version: 2
  build_test:
    jobs:
      - build:
          filters:
            branches:
              only: circle-ci
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - restore_cache:
          key: deps2-{{ checksum "requirements.txt" }}
      - run:
          name: Installing modules
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps2-{{ checksum "requirements.txt" }}
          paths:
            - 'venv'
      - run:
          name: Testing 
          command: |
            . venv/bin/activate
            python3 -m pytest tests
      - store_artifacts:
          path: test-reports/
          destination: tr1
      - store_test_results:
          path: test-reports/