workflows:
  version: 2
  build_test:
    jobs:
      - build:
          filters:
            branches:
              only: circle-ci
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Installing modules
          command: |
            pip3 install requirements.txt
      - run:
          name: Testing 
          command: |
            python3 -m pytest tests