version: 2
general:
  branches:
    only:
     - sklearn
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: /

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            flake8 --exclude=venv* --statistics
            python3 -m unittest tests/test.py